GET {{host}}:{{port}}{{pattern}}/route

###
GET {{host}}:{{port}}{{pattern}}/route/{{routeId}}

####
POST {{host}}:{{port}}{{pattern}}/route
Content-Type: application/json; charset=UTF-8

{
  "id": "livk-dynamic",
  "predicates": [
    {
      "name": "Path",
      "args": {
        "_genkey_0": "/api/dynamic/**"
      }
    }
  ],
  "filters": [
    {
      "name": "StripPrefix",
      "args": {
        "parts": "2"
      }
    }
  ],
  "uri": "lb://api-dynamic",
  "metadata": {
    "username": "livk",
    "password": "123456",
    "register": "nacos"
  },
  "order": 0,
  "description": "dynamic Route",
  "status": 1
}

###
DELETE {{host}}:{{port}}{{pattern}}/route/{{routeId}}

###
POST {{host}}:{{port}}{{pattern}}/route/reload
